{
 "title": "Charges",
 "description": "Overview over all charging sessions",
 "tags": [ "vwsfriend" ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles"
   },
   {
    "name": "vwsfriend_url",
    "query": "SELECT vwsfriend_url FROM settings LIMIT 1"
   },
   {
    "name": "tag",
    "label": "Show",
    "query": "SELECT tag.name || ': ' || tag.description || '$' || tag.name FROM charging_tag LEFT JOIN tag ON charging_tag.tag_name = tag.name WHERE use_charges = true"
   },
   {
    "name": "tag_sql",
    "query": "SELECT CASE WHEN LENGTH($$${tag:raw}$$)>0 AND $$${tag:singlequote}$$ != 'all_values' THEN $$ AND charging_tag.tag_name IN (${tag:singlequote}) $$ ELSE '' END"
   }
  ]
 },
 "panels": [
  {
   "title": "Charges",
   "type": "table",
   "description": "List of all charging sessions recorded. Not all attributes can be filled automatically. If you want to make additions or changes use the ⚙ button at the end of each row. If a charging session is missing use the \"Add Charging\" button.",
   "gridPos": { "h": 26, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"start_date\" AS \"Date\",\n  \"Location\",\n  \"maximumChargePower_kW\" AS \"Max. Power\",\n  \"Avg. Power\",\n  \"AC/DC\",\n  \"% Start\",\n  \"% End\",\n  \"Amount\",\n  \"✓\",\n  \"Cost\",\n  \"Odometer\",\n  (\"Amount\"\n    - (\"endSOC_pct\" - lag(\"endSOC_pct\") over (order by start_date)) * (\"vehicle_capacity\" / 100::NUMERIC)) / NULLIF(((\"Odometer\" - lag(\"Odometer\") over (order by start_date)) / 100::NUMERIC), 0) AS \"Consumption\",\n  \"Edit\",\n  \"id\",\n  (round(extract(epoch FROM start_date) - 10) * 1000) AS start_date_ts,\n  COALESCE((round(extract(epoch FROM end_date) - 10) * 1000)::TEXT,'now') AS end_date_ts\nFROM\n  (SELECT DISTINCT\n    COALESCE (started, COALESCE (locked, connected)) AS start_date,\n    COALESCE (ended, COALESCE (unlocked, disconnected)) AS end_date,\n    COALESCE(locations.\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', locations.name, locations.amenity), nullif(CONCAT_WS(' ', locations.road, locations.house_number), '')), locations.neighbourhood, locations.city, locations.postcode, locations.country)) AS \"Location\",\n    EXTRACT('epoch' FROM (COALESCE (ended, COALESCE (unlocked, disconnected)) - COALESCE (started, COALESCE (locked, connected)))) AS \"Duration\",\n    \"maximumChargePower_kW\",\n    (COALESCE(\"realCharged_kWh\",(\"endSOC_pct\" - \"startSOC_pct\") * (\n      CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n           ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n      END\n      / 100::NUMERIC))) / (EXTRACT(epoch FROM (COALESCE(ended, COALESCE(unlocked, disconnected)) - COALESCE(started, COALESCE (locked, connected))))::NUMERIC / 3600::NUMERIC) AS \"Avg. Power\",\n    acdc AS \"AC/DC\",\n    \"startSOC_pct\" AS \"% Start\",\n    \"endSOC_pct\" AS \"% End\",\n    COALESCE(\"realCharged_kWh\",\n    (\"endSOC_pct\" - \"startSOC_pct\") * (\n      CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n           ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n      END\n      / 100::NUMERIC)) AS \"Amount\",\n    CASE WHEN \"realCharged_kWh\" IS NOT NULL THEN '✓'\n         ELSE NULL\n    END AS \"✓\",\n    \"realCost_ct\"::NUMERIC/ 100 AS \"Cost\",\n    \"mileage_km\" AS \"Odometer\",\n    '⚙' AS \"Edit\",\n    id,\n    \"endSOC_pct\",\n    (CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END) AS \"vehicle_capacity\"\n  FROM charging_sessions\n  LEFT JOIN locations ON charging_sessions.location_id = locations.osm_id\n  LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n  LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n  LEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\n  WHERE\n    ($__timeFilter(started) OR $__timeFilter(connected) OR $__timeFilter(locked)) AND\n    charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}\n ) AS result\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Top 10 Chargers",
   "type": "table",
   "description": "List of the most often used charging stations. If this list is empty your car probably does not provide a location. You can still set charging stations by using the ⚙ button in the list of charging sessions.",
   "gridPos": { "h": 13, "w": 5, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Charger\",\n  COUNT(\"Session\") AS \"Sessions\",\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n    chargers.name AS \"Charger\",\n    charging_sessions.id AS \"Session\",\n    COALESCE(\"realCharged_kWh\",\n    (\"endSOC_pct\" - \"startSOC_pct\") * (\n      CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n           ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n      END) / 100::NUMERIC) AS \"Amount\"\n  FROM charging_sessions\n  LEFT JOIN chargers ON charging_sessions.charger_id = chargers.id\n  LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n  LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n  LEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\n  WHERE\n    ($__timeFilter(started) OR $__timeFilter(connected) OR $__timeFilter(locked)) AND\n    chargers.name IS NOT NULL AND\n    charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}) AS result\nGROUP BY result.\"Charger\"\nORDER BY \"Sessions\" DESC, \"Amount\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Operators",
   "type": "table",
   "description": "List of the most often used charging operators. If this list is empty your car probably does not provide a location. You can still set charging stations by using the ⚙ button in the list of charging sessions.",
   "gridPos": { "h": 13, "w": 5, "x": 17, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Operator\",\n  COUNT(\"Session\") AS \"Sessions\",\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n    operators.name AS \"Operator\",\n    charging_sessions.id AS \"Session\",\n    COALESCE(\"realCharged_kWh\",\n    (\"endSOC_pct\" - \"startSOC_pct\") * (\n      CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n           ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n      END) / 100::NUMERIC) AS \"Amount\"\n  FROM charging_sessions\n  LEFT JOIN chargers ON charging_sessions.charger_id = chargers.id\n  LEFT JOIN operators ON chargers.operator_id = operators.id\n  LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n  LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n  LEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\n  WHERE\n    ($__timeFilter(started) OR $__timeFilter(connected) OR $__timeFilter(locked)) AND\n    chargers.name IS NOT NULL AND\n    charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}) AS result\nGROUP BY result.\"Operator\"\nORDER BY \"Sessions\" DESC, \"Amount\" DESC\nLIMIT 10"
    }
   ]
  }
 ]
}