{
 "title": "Charging Statistics",
 "tags": [ "vwsfriend" ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles"
   },
   {
    "name": "car_timezone",
    "label": "The Cars timezone",
    "query": "SELECT COALESCE(timezone, 'UTC') FROM vehicle_settings WHERE vehicle_vin='$VIN'"
   },
   {
    "name": "tag",
    "label": "Show",
    "query": "SELECT tag.name || ': ' || tag.description || '$' || tag.name FROM charging_tag LEFT JOIN tag ON charging_tag.tag_name = tag.name WHERE use_charges = true"
   },
   {
    "name": "tag_sql",
    "query": "SELECT CASE WHEN LENGTH($$${tag:raw}$$)>0 AND $$${tag:singlequote}$$ != 'all_values' THEN $$ AND charging_tag.tag_name IN (${tag:singlequote}) $$ ELSE '' END"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Charges",
   "type": "stat",
   "description": "Total number of charging sessions recorded.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT charging_sessions.id) AS \"Number of Charges\"\nFROM charging_sessions\nLEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\nWHERE\n  ($__timeFilter(\"started\") OR $__timeFilter(\"ended\")) AND\n  charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}"
    }
   ]
  },
  {
   "title": "Total Cycles",
   "type": "stat",
   "description": "Total number of battery cycles. A charge cycle happens when you use all of the battery’s power—but that doesn’t necessarily mean in a single charge.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(charging_sessions.\"endSOC_pct\" - charging_sessions.\"startSOC_pct\")/100 AS \"Number of Charges\"\nFROM charging_sessions\nLEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\nWHERE\n  ($__timeFilter(\"started\") OR $__timeFilter(\"ended\")) AND\n  charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}"
    }
   ]
  },
  {
   "title": "Charge map",
   "type": "panodata-map-panel",
   "description": "Charging locations: Size and color corresponds to energy charged at that station.\nLocations are only recorded when provided from the car.\nEnergy is taken from exact value that was added to the charging sessions or estimated based on SoC if no exact data is available.",
   "gridPos": { "h": 20, "w": 13, "x": 8, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  \"final_latitude\",\n  \"final_longitude\",\n  \"Charger\",\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n  charging_sessions.id,\n  COALESCE(chargers.latitude, ROUND(charging_sessions.\"position_latitude\"::NUMERIC,3)) AS \"final_latitude\",\n  COALESCE(chargers.longitude, ROUND(charging_sessions.\"position_longitude\"::NUMERIC,3)) AS \"final_longitude\",\n  COALESCE(chargers.name, 'unkown') AS \"Charger\",\n  COALESCE(\"realCharged_kWh\",\n  (\"endSOC_pct\" - \"startSOC_pct\") * (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END\n    / 100::NUMERIC)) AS \"Amount\"\nFROM charging_sessions\nLEFT JOIN locations ON charging_sessions.location_id = locations.osm_id\nLEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nLEFT JOIN chargers ON charging_sessions.\"charger_id\" = chargers.id\nLEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\nWHERE\n  COALESCE(chargers.latitude, charging_sessions.\"position_latitude\") IS NOT NULL AND\n  COALESCE(chargers.longitude, charging_sessions.\"position_longitude\") IS NOT NULL AND\n  ($__timeFilter(started) OR $__timeFilter(connected) OR $__timeFilter(locked)) AND\n  charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}) AS result\nGROUP BY \"final_latitude\", \"final_longitude\", \"Charger\""
    }
   ]
  },
  {
   "title": "Total Amount",
   "type": "stat",
   "description": "Total energy charged.\nEnergy is taken from exact value that was added to the charging sessions or estimated based on SoC if no exact data is available.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n       charging_sessions.id,\n       COALESCE(\"realCharged_kWh\",\n      (\"endSOC_pct\" - \"startSOC_pct\") * (\n        CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n             ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n        END\n        / 100::NUMERIC)) AS \"Amount\"\n    FROM charging_sessions\n    LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n    LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n    LEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\n    WHERE\n      ($__timeFilter(\"started\") OR $__timeFilter(\"ended\")) AND\n      charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}) AS result"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "description": "Sum of all charging costs.\nCharging costs can be added in each charging session.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"realCost_ct\"::NUMERIC/100::NUMERIC) AS \"Cost\"\nFROM\n  (SELECT DISTINCT\n       charging_sessions.id,\n       \"realCost_ct\"\n    FROM charging_sessions\n    LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n    LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n    LEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\n    WHERE\n      ($__timeFilter(\"started\") OR $__timeFilter(\"ended\")) AND\n      charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}) AS result"
    }
   ]
  },
  {
   "title": "Difference estimated/real",
   "type": "stat",
   "description": "Difference between estimated energy charged from the car and real energy charged.\nValue is calculated if charging sessions have real energy charged added.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (SUM(\"Estimated\") - SUM(\"realCharged_kWh\")) / SUM(\"realCharged_kWh\") * 100 AS \"Delta %\"\nFROM\n  (SELECT DISTINCT\n       charging_sessions.id AS id,\n       ((\"endSOC_pct\" - \"startSOC_pct\") * (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END\n    / 100::NUMERIC))::NUMERIC AS \"Estimated\",\n    \"realCharged_kWh\"::NUMERIC\n    FROM charging_sessions\n    LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n    LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n    LEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\n    WHERE\n      ($__timeFilter(\"started\") OR $__timeFilter(\"ended\")) AND\n      \"realCharged_kWh\" IS NOT NULL AND \"endSOC_pct\" IS NOT NULL AND \"startSOC_pct\" IS NOT NULL AND\n      charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw}) AS result"
    }
   ]
  },
  { "type": "timeseries", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 } },
  {
   "title": "AC/DC",
   "type": "piechart",
   "description": "Energy added by AC/DC charging sessions.\nAC/DC can be automatically detected if provided from the car. If not it is guessed based on charge power. If the charge power is not available AC/DC can be manually set in the charging sessions.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Type\",\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n     charging_sessions.id, \n     COALESCE(acdc::TEXT, 'unknown') AS \"Type\",\n     COALESCE(\"realCharged_kWh\",\n    (\"endSOC_pct\" - \"startSOC_pct\") * (\n      CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n           ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n      END\n      / 100::NUMERIC)) AS \"Amount\"\n  FROM charging_sessions\n  LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n  LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n  LEFT JOIN charging_tag ON charging_sessions.id = charging_tag.charging_sessions_id\n  WHERE\n    ($__timeFilter(\"started\") OR $__timeFilter(\"ended\")) AND\n    charging_sessions.vehicle_vin = '$VIN' ${tag_sql:raw} AND\n    (\"realCharged_kWh\" IS NOT NULL OR \"endSOC_pct\" != \"startSOC_pct\")) AS result\nGROUP BY \"Type\""
    }
   ]
  },
  {
   "title": "Charging Load",
   "type": "piechart",
   "description": "Amount of  Energy loaded above and below 0.8C.\n1C corresponds to the power necessary to load the car in 1hour to its full capacity.\nGross battery capacity must be set in the vehicles settings.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "(SELECT\n '<0.8C' AS \"Type\",\n SUM(\"chargePower_kW\") / (SELECT SUM(\"chargePower_kW\") FROM charges) * 100 AS \"Amount\"\nFROM charges\nLEFT JOIN vehicles ON charges.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON charges.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  charges.\"chargePower_kW\" <= (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity_total\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity_total\"::NUMERIC\n    END\n    * 0.8) AND\n  charges.\"chargingState\" = 'CHARGING' AND\n  charges.vehicle_vin = '$VIN')\nUNION\nSELECT\n '>0.8C' AS label,\n SUM(\"chargePower_kW\") / (SELECT SUM(\"chargePower_kW\") FROM charges) * 100 AS \"Amount\"\nFROM charges\nLEFT JOIN vehicles ON charges.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON charges.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  charges.\"chargePower_kW\" > (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity_total\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity_total\"::NUMERIC\n    END\n    * 0.8) AND\n  charges.\"chargingState\" = 'CHARGING' AND\n  charges.vehicle_vin = '$VIN'"
    }
   ]
  },
  {
   "title": "Power distribution",
   "type": "natel-plotly-panel",
   "description": "Distribution of the power used for charging.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n width_bucket(\"chargePower_kW\",-5,205,21) AS power,\n (((width_bucket(\"chargePower_kW\",-5,205,21)-1.5)*(210/21)))::TEXT || 'kW to ' || (((width_bucket(\"chargePower_kW\",-5,205,21)-0.5)*(210/21)))::TEXT || 'kW' AS metric,\n ((width_bucket(\"chargePower_kW\",-5,205,21)::decimal-1)*(210/21)) AS middle,\n SUM(\"chargePower_kW\") / (SELECT SUM(\"chargePower_kW\") FROM charges) * 100 AS Amount\nFROM charges\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  charges.\"chargingState\" = 'CHARGING' AND\n  charges.vehicle_vin = '$VIN'\nGROUP BY power, metric, middle\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly distribution in timezone $car_timezone",
   "type": "natel-plotly-panel",
   "description": "Distribution of the charging time over the day.\nFor meaningful values wait until a significant number of charging sessions were recorded. Change timezone in vehicle settings.",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n EXTRACT(HOUR FROM ((\"carCapturedTimestamp\"::timestamp AT TIME ZONE 'UTC') AT TIME ZONE COALESCE(vehicle_settings.timezone, 'UTC'))) AS \"Hour\",\n (COUNT(*) / CAST( SUM(COUNT(*)) over () as FLOAT) * 100) AS \"Number\",\n ROUND((COUNT(*) / CAST( SUM(COUNT(*)) over () as FLOAT) * 100))::TEXT || '% of charging time' AS \"Text\"\nFROM charges\nLEFT JOIN vehicle_settings ON charges.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  charges.\"chargingState\" = 'CHARGING' AND\n  charges.vehicle_vin = '$VIN'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DC Charging Speed by SoC",
   "type": "natel-plotly-panel",
   "description": "Charging speeds at different SoC.\nFor meaningful values wait until a significant number of charging sessions were recorded. Only DC charging sessions are considered.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  battery.\"currentSOC_pct\" AS \"soc\",\n  MAX(charges.\"chargePower_kW\") AS \"max\",\n  AVG(charges.\"chargePower_kW\") AS \"avg\",\n  MIN(charges.\"chargePower_kW\") AS \"min\",\n  'max. ' || MAX(charges.\"chargePower_kW\")::TEXT || 'kW from ' || COUNT(charges.\"chargePower_kW\")::TEXT  || ' values' AS \"maxText\",\n  'avg. ' || ROUND(AVG(charges.\"chargePower_kW\")::DECIMAL,2)::TEXT || 'kW from ' || COUNT(charges.\"chargePower_kW\")::TEXT  || ' values' AS \"avgText\",\n  'min. ' || MIN(charges.\"chargePower_kW\")::TEXT || 'kW from ' || COUNT(charges.\"chargePower_kW\")::TEXT  || ' values' AS \"minText\"\nFROM\n  charges\nINNER JOIN charging_sessions ON charges.\"carCapturedTimestamp\" > charging_sessions.started AND charges.\"carCapturedTimestamp\" < charging_sessions.ended\nINNER JOIN battery ON battery.\"carCapturedTimestamp\" = (SELECT battery.\"carCapturedTimestamp\" FROM battery WHERE battery.\"carCapturedTimestamp\" > charges.\"carCapturedTimestamp\" - interval '120 SECONDS' AND battery.\"carCapturedTimestamp\" < charges.\"carCapturedTimestamp\" + interval '120 SECONDS' ORDER BY ABS(EXTRACT(epoch FROM (battery.\"carCapturedTimestamp\" - charges.\"carCapturedTimestamp\"))) ASC LIMIT 1)\nWHERE\n    charging_sessions.acdc = 'DC' AND\n    charges.\"chargePower_kW\" > 0 AND\n    $__timeFilter(charges.\"carCapturedTimestamp\") AND\n    charges.vehicle_vin = '$VIN'\nGROUP BY soc\nORDER by soc ASC"
    }
   ]
  }
 ]
}