{
 "title": "Journey",
 "tags": [ "vwsfriend" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles"
   },
   {
    "name": "vwsfriend_url",
    "query": "SELECT vwsfriend_url FROM settings LIMIT 1"
   },
   {
    "name": "tripstart",
    "query": "SELECT\n    (FIRST_VALUE(\"startDate\") OVER sd)  - INTERVAL '10' SECOND AS \"Start\"\n  FROM trips\n  WHERE\n    ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n    trips.vehicle_vin = '$VIN'\n  WINDOW sd as (ORDER BY \"startDate\" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\n  LIMIT 1"
   },
   {
    "name": "tripend",
    "query": "SELECT\n    LAST_VALUE(\"endDate\") OVER sd  + INTERVAL '10' SECOND AS \"End\"\n  FROM trips\n  WHERE\n    ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n    trips.vehicle_vin = '$VIN'\n  WINDOW sd as (ORDER BY \"startDate\" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\n  LIMIT 1"
   },
   { "name": "title" }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "(SELECT\n  $__time(\"startDate\"),\n  trips.start_position_latitude AS latitude\nFROM trips\nWHERE\n  $__timeFilter(\"startDate\") AND\n  trips.vehicle_vin = '$VIN'\nUNION\nSELECT\n  $__time(\"endDate\"),\n  trips.destination_position_latitude AS latitude\nFROM trips\nWHERE\n  $__timeFilter(\"endDate\") AND\n  trips.vehicle_vin = '$VIN'\n)\nORDER BY 1"
    },
    {
     "rawSql": "(SELECT\n  $__time(\"startDate\"),\n  trips.start_position_longitude AS longitude\nFROM trips\nWHERE\n  $__timeFilter(\"startDate\") AND\n  trips.vehicle_vin = '$VIN'\nUNION\nSELECT\n  $__time(\"endDate\"),\n  trips.destination_position_longitude AS longitude\nFROM trips\nWHERE\n  $__timeFilter(\"endDate\") AND\n  trips.vehicle_vin = '$VIN'\n  )\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${title} From / To",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nfromlocation.display_name AS \"From\",\ntolocation.display_name AS \"To\"\nFROM\n(SELECT\n  FIRST_VALUE(\"start_location_id\") OVER sd AS \"fromid\",\n  LAST_VALUE(\"destination_location_id\") OVER sd AS \"toid\"\nFROM trips\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\nWINDOW sd as (ORDER BY \"startDate\" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\nLIMIT 1) AS fromto\nJOIN locations AS fromlocation ON  fromlocation.osm_id = fromto.fromid\nJOIN locations AS tolocation ON  tolocation.osm_id = fromto.toid"
    }
   ]
  },
  {
   "title": "Details",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH dates AS\n(\n  SELECT\n    vehicle_vin,\n    FIRST_VALUE(\"startDate\") OVER sd AS \"Start\",\n    LAST_VALUE(\"endDate\") OVER sd AS \"End\"\n  FROM trips\n  WHERE\n    ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n    trips.vehicle_vin = '$VIN'\n  WINDOW sd as (ORDER BY \"startDate\" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\n  LIMIT 1\n),\nenergy_charged AS\n(\n  SELECT\n    SUM(COALESCE(\"realCharged_kWh\",\n    (\"endSOC_pct\" - \"startSOC_pct\") * (\n      CASE\n        WHEN\n          vehicles.\"carType\" = 'ELECTRIC'\n        THEN\n          vehicle_settings.\"primary_capacity\"::NUMERIC\n        ELSE\n          vehicle_settings.\"secondary_capacity\"::NUMERIC\n      END\n      / 100::NUMERIC))) AS \"Energy Charged\"\n  FROM \n    charging_sessions\n  LEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\n  LEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n  WHERE\n    $__timeFilter(\"started\") AND\n    charging_sessions.vehicle_vin = '$VIN'  \n),\nrefueled AS\n(\n  SELECT\n    SUM(COALESCE(\"realRefueled_l\",\n    (\"endSOC_pct\" - \"startSOC_pct\") * ( \n      vehicle_settings.\"primary_capacity\"::NUMERIC\n      / 100::NUMERIC))) AS \"Refueled\"\n  FROM \n    refuel_sessions\n  LEFT JOIN vehicles ON refuel_sessions.vehicle_vin = vehicles.vin\n  LEFT JOIN vehicle_settings ON refuel_sessions.vehicle_vin = vehicle_settings.vehicle_vin\n  WHERE\n    $__timeFilter(\"date\") AND\n    refuel_sessions.vehicle_vin = '$VIN'  \n)\n\nSELECT\n  *,\n  \"Energy used (estimated)\" / \"Length\" * 100 AS \"Energy consumption / 100km\",\n  \"Gasoline used (estimated)\" / \"Length\" * 100 AS \"Gasoline consumption / 100km\"\nFROM\n  (\n    SELECT\n      FIRST_VALUE(\"startDate\") OVER sd AS \"Start\",\n      LAST_VALUE(\"endDate\") OVER sd AS \"End\",\n      FIRST_VALUE(\"start_mileage_km\") OVER sd AS \"Start Mileage\",\n      LAST_VALUE(\"end_mileage_km\") OVER sd AS \"End Mileage\",\n      (LAST_VALUE(\"end_mileage_km\") OVER sd)-(FIRST_VALUE(\"start_mileage_km\") OVER sd) AS \"Length\",\n      (\n        SELECT\n          (startbattery.\"currentSOC_pct\" - endbattery.\"currentSOC_pct\") * (\n            CASE\n              WHEN\n                vehicles.\"carType\" = 'ELECTRIC'\n              THEN\n                vehicle_settings.\"primary_capacity\"::NUMERIC\n              ELSE\n                vehicle_settings.\"secondary_capacity\"::NUMERIC\n            END\n            / 100::NUMERIC) + (\n              SELECT COALESCE(\"Energy Charged\",0) FROM energy_charged\n            ) AS \"Energy used (estimated)\"\n        FROM\n          dates\n        LEFT JOIN vehicles ON dates.vehicle_vin = vehicles.vin\n        LEFT JOIN vehicle_settings ON dates.vehicle_vin = vehicle_settings.vehicle_vin\n        JOIN battery AS startbattery ON startbattery.\"carCapturedTimestamp\" = (SELECT \"carCapturedTimestamp\" FROM battery WHERE \"carCapturedTimestamp\" > \"Start\" - interval '600 SECONDS' AND \"carCapturedTimestamp\" < \"Start\" + interval '600 SECONDS' ORDER BY ABS(EXTRACT(epoch FROM (\"carCapturedTimestamp\" - \"Start\"))) ASC LIMIT 1)\n        JOIN battery AS endbattery ON endbattery.\"carCapturedTimestamp\" = (SELECT \"carCapturedTimestamp\" FROM battery WHERE \"carCapturedTimestamp\" > \"End\" - interval '600 SECONDS' AND \"carCapturedTimestamp\" < \"End\" + interval '600 SECONDS' ORDER BY ABS(EXTRACT(epoch FROM (\"carCapturedTimestamp\" - \"End\"))) ASC LIMIT 1)\n      ) AS \"Energy used (estimated)\",\n      (\n        SELECT\n          CASE\n            WHEN\n              vehicles.\"carType\" != 'ELECTRIC'\n            THEN\n              (startranges.\"primary_currentSOC_pct\" - endranges.\"primary_currentSOC_pct\") * (vehicle_settings.\"primary_capacity\"::NUMERIC\n                / 100::NUMERIC) + (\n                  SELECT COALESCE(\"Refueled\",0) FROM refueled\n                )\n            ELSE\n              NULL\n            END AS \"Gasoline used (estimated)\"\n        FROM\n          dates\n        LEFT JOIN vehicles ON dates.vehicle_vin = vehicles.vin\n        LEFT JOIN vehicle_settings ON dates.vehicle_vin = vehicle_settings.vehicle_vin\n        JOIN ranges AS startranges ON startranges.\"carCapturedTimestamp\" = (SELECT \"carCapturedTimestamp\" FROM ranges WHERE \"carCapturedTimestamp\" > \"Start\" - interval '600 SECONDS' AND \"carCapturedTimestamp\" < \"Start\" + interval '600 SECONDS' ORDER BY ABS(EXTRACT(epoch FROM (\"carCapturedTimestamp\" - \"Start\"))) ASC LIMIT 1)\n        JOIN ranges AS endranges ON endranges.\"carCapturedTimestamp\" = (SELECT \"carCapturedTimestamp\" FROM ranges WHERE \"carCapturedTimestamp\" > \"End\" - interval '600 SECONDS' AND \"carCapturedTimestamp\" < \"End\" + interval '600 SECONDS' ORDER BY ABS(EXTRACT(epoch FROM (\"carCapturedTimestamp\" - \"End\"))) ASC LIMIT 1)\n      ) AS \"Gasoline used (estimated)\"\n    FROM trips\n    WHERE\n      ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n      trips.vehicle_vin = '$VIN'\n    WINDOW sd as (ORDER BY \"startDate\" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\n    LIMIT 1\n  ) AS precalc"
    }
   ]
  },
  {
   "title": "Time",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  'Charging' AS \"type\",\n  EXTRACT(EPOCH FROM SUM(COALESCE(\"ended\", \"unlocked\", \"disconnected\") - COALESCE(\"started\", \"locked\", \"connected\"))) AS \"Time\"\nFROM charging_sessions\nWHERE\n  ($__timeFilter(\"started\") OR $__timeFilter(\"ended\")) AND\n  vehicle_vin = '$VIN'\nUNION\nSELECT\n  'Driving' AS \"type\",\n  EXTRACT(EPOCH FROM SUM(\"endDate\"-\"startDate\")) AS \"Time\"\nFROM trips\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  vehicle_vin = '$VIN'"
    }
   ]
  },
  {
   "title": "States",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Charging State",
     "rawSql": "(\nSELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"chargingState\"::TEXT AS \"State\"\nFROM charges\nWHERE\n  (\"chargingState\" = 'CHARGING' OR \"chargingState\" = 'OFF' OR \"chargingState\" = 'READY_FOR_CHARGING') AND\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nUNION\nSELECT\n  \"startDate\" AS time,\n  'DRIVING' AS \"State\"\nFROM trips\nWHERE\n  $__timeFilter(\"startDate\") AND\n  vehicle_vin = '$VIN'\nUNION\nSELECT\n  \"endDate\" AS time,\n  'OFF' AS \"State\"\nFROM trips\nWHERE\n  $__timeFilter(\"endDate\") AND\n  vehicle_vin = '$VIN'\n)\nORDER BY 1  "
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"cruisingRangeElectric_km\" AS \"Electric Range\"\nFROM battery\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1  "
    },
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"currentSOC_pct\" AS \"Battery SoC\"\nFROM battery\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Trips",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"startDate\" AS \"Start Date\",\n  start_locations.display_name AS \"Start Location\",\n  destination_location.display_name AS \"Destination Location\",\n  (\"endDate\"-\"startDate\") AS \"Duration\",\n  (\"end_mileage_km\"-\"start_mileage_km\") AS \"Length\",\n  \"end_mileage_km\" AS \"Odometer\",\n  '⚙' AS \"Edit\",\n  id,\n  COALESCE((round(extract(epoch FROM \"startDate\") - 300) * 1000)::TEXT,'now-1d') AS start_date_ts,\n  COALESCE((round(extract(epoch FROM \"endDate\") + 300) * 1000)::TEXT,'now') AS end_date_ts\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Charges",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE (started, COALESCE (locked, connected)) AS \"Date\",\n  locations.display_name AS \"Location\",\n  COALESCE (ended, COALESCE (unlocked, disconnected)) - COALESCE (started, COALESCE (locked, connected)) AS \"Duration\",\n  \"maximumChargePower_kW\" AS \"Max. Power\",\n  ((\"endSOC_pct\" - \"startSOC_pct\") * (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END\n    / 100::NUMERIC)) / (EXTRACT(epoch FROM (COALESCE(ended, COALESCE(unlocked, disconnected)) - COALESCE(started, COALESCE (locked, connected))))::NUMERIC / 3600::NUMERIC) AS \"Avg. Power\",\n  acdc AS \"AC/DC\",\n  \"startSOC_pct\" AS \"% Start\",\n  \"endSOC_pct\" AS \"% End\",\n  COALESCE(\"realCharged_kWh\",\n  (\"endSOC_pct\" - \"startSOC_pct\") * (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END\n    / 100::NUMERIC)) AS \"Amount\",\n  CASE WHEN \"realCharged_kWh\" IS NOT NULL THEN '✓'\n       ELSE NULL\n  END AS \"✓\",\n  \"realCost_ct\"::NUMERIC/ 100 AS \"Cost\",\n  \"mileage_km\" AS \"Odometer\",\n  '⚙' AS \"Edit\",\n  id,\n  (round(extract(epoch FROM COALESCE (started, COALESCE (locked, connected))) - 10) * 1000) AS start_date_ts,\n  COALESCE((round(extract(epoch FROM COALESCE (ended, COALESCE (unlocked, disconnected))) - 10) * 1000)::TEXT,'now') AS end_date_ts\nFROM charging_sessions\nLEFT JOIN locations ON charging_sessions.location_id = locations.osm_id\nLEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  ($__timeFilter(started) OR $__timeFilter(connected) OR $__timeFilter(locked)) AND\n  charging_sessions.vehicle_vin = '$VIN'\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Refueling",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"Date\",\n  locations.display_name AS \"Location\",\n  \"startSOC_pct\" AS \"% Start\",\n  \"endSOC_pct\" AS \"% End\",\n   (\"endSOC_pct\" - \"startSOC_pct\") * (vehicle_settings.\"primary_capacity\"::NUMERIC / 100::NUMERIC) AS \"Amount\",\n  CASE WHEN \"realRefueled_l\" IS NOT NULL THEN '✓'\n       ELSE NULL\n  END AS \"✓\",\n  \"realCost_ct\"::NUMERIC/ 100 AS \"Cost\",\n  \"mileage_km\" AS \"Odometer\",\n  '⚙' AS \"Edit\",\n  id,\n  (round(extract(epoch FROM date)) * 1000) AS start_date_ts\nFROM refuel_sessions\nLEFT JOIN locations ON refuel_sessions.location_id = locations.osm_id\nLEFT JOIN vehicles ON refuel_sessions.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON refuel_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  $__timeFilter(date) AND\n  refuel_sessions.vehicle_vin = '$VIN'\nORDER BY date"
    }
   ]
  }
 ]
}