{
 "title": "Maintenance",
 "description": "Overview over maintenance related data",
 "tags": [ "vwsfriend" ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles"
   }
  ]
 },
 "panels": [
  {
   "title": "Warning Lights",
   "type": "table",
   "description": "List of all warning light occurrences. Not all cars provide this information",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"start\" AS \"From\",\n  \"start_mileage\" AS \"From Mileage\",\n  \"end\" AS \"To\",\n  \"end_mileage\" AS \"To Mileage\",\n  EXTRACT('epoch' FROM (\"end\"-\"start\")) AS \"Duration\",\n  \"end_mileage\"-\"start_mileage\" AS \"Length\",\n  \"messageId\" AS \"Message ID\",\n  \"text\" AS \"Message\",\n  \"category\" AS \"Category\",\n  \"priority\" AS \"Priority\"\nFROM warning_lights\nWHERE\n  ($__timeFilter(\"start\") OR $__timeFilter(\"end\")) AND\n    warning_lights.vehicle_vin = '$VIN'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Service due",
   "type": "stat",
   "description": "Next regular service due in. Not all cars provide this data.",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NULL AS \"Oil service due in days\",\n  NULL AS \"Oil service due in Km\",\n  due_in_days AS \"Inspection due in days\",\n  due_in_km AS \"Inspection due in Km\"\nFROM maintenance\nWHERE\n    date is NULL AND\n    type = 'INSPECTION' AND\n    maintenance.vehicle_vin = '$VIN'\nUNION\nSELECT\n  due_in_days AS \"Oil service due in days\",\n  due_in_km AS \"Oil service due in Km\",\n  NULL AS \"Inspection due in days\",\n  NULL AS \"Inspection due in Km\"\nFROM maintenance\nWHERE\n    date is NULL AND\n    type = 'OIL_SERVICE' AND\n    maintenance.vehicle_vin = '$VIN'"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "table",
   "description": "List of all detected maintenance occurrences. Not all cars provide this information",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"Date\",\n  mileage AS \"Mileage\",\n  type AS \"Service type\",\n  \"due_in_days\" AS \"Was due in days\",\n  \"due_in_km\" AS \"Was due in km\"\nFROM maintenance\nWHERE\n    date IS NOT NULL AND\n    maintenance.vehicle_vin = '$VIN'\nORDER BY 1"
    }
   ]
  }
 ]
}