{
 "title": "Refueling",
 "tags": [ "vwsfriend" ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles WHERE vehicles.\"carType\" != 'ELECTRIC'"
   },
   {
    "name": "vwsfriend_url",
    "query": "SELECT vwsfriend_url FROM settings LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Refueling",
   "type": "table",
   "gridPos": { "h": 26, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"Date\",\n  COALESCE(\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', name, amenity), nullif(CONCAT_WS(' ', road, house_number), '')), neighbourhood, city, postcode, country)) AS \"Location\",\n  \"startSOC_pct\" AS \"% Start\",\n  \"endSOC_pct\" AS \"% End\",\n    COALESCE(\"realRefueled_l\",(\"endSOC_pct\" - \"startSOC_pct\") * (vehicle_settings.\"primary_capacity\"::NUMERIC / 100::NUMERIC)) AS \"Amount\",\n  CASE WHEN \"realRefueled_l\" IS NOT NULL THEN '✓'\n       ELSE NULL\n  END AS \"✓\",\n  \"realCost_ct\"::NUMERIC/ 100 AS \"Cost\",\n  \"mileage_km\" AS \"Odometer\",\n  (COALESCE(\"realRefueled_l\",(\"endSOC_pct\" - \"startSOC_pct\") * (vehicle_settings.\"primary_capacity\"::NUMERIC / 100::NUMERIC))\n    - (\"endSOC_pct\" - lag(\"endSOC_pct\") over (order by date)) * (vehicle_settings.\"primary_capacity\"::NUMERIC / 100::NUMERIC)) / NULLIF(((\"mileage_km\" - lag(mileage_km) over (order by date)) / 100::NUMERIC), 0) AS \"Consumption\",\n  '⚙' AS \"Edit\",\n  id,\n  (round(extract(epoch FROM date)) * 1000) AS start_date_ts\nFROM refuel_sessions\nLEFT JOIN locations ON refuel_sessions.location_id = locations.osm_id\nLEFT JOIN vehicles ON refuel_sessions.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON refuel_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  $__timeFilter(date) AND\n  refuel_sessions.vehicle_vin = '$VIN'\nORDER BY date DESC"
    }
   ]
  },
  {
   "title": "Top 10 Stations",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  locations.display_name AS \"Station\",\n  COUNT(refuel_sessions.id) AS \"Sessions\",\n  SUM(COALESCE(\"realRefueled_l\",\n  (\"endSOC_pct\" - \"startSOC_pct\") * (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END) / 100::NUMERIC)) AS \"Amount\"\nFROM refuel_sessions\nLEFT JOIN locations ON refuel_sessions.location_id = locations.osm_id\nLEFT JOIN vehicles ON refuel_sessions.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON refuel_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  $__timeFilter(date) AND\n  locations.display_name IS NOT NULL AND\n  refuel_sessions.vehicle_vin = '$VIN'\nGROUP BY locations.osm_id\nORDER BY \"Sessions\" DESC, \"Amount\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Operators",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 17, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  locations.amenity AS \"Operator\",\n  COUNT(refuel_sessions.id) AS \"Sessions\",\n  SUM(COALESCE(\"realRefueled_l\",\n  (\"endSOC_pct\" - \"startSOC_pct\") * (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END) / 100::NUMERIC)) AS \"Amount\"\nFROM refuel_sessions\nLEFT JOIN locations ON refuel_sessions.location_id = locations.osm_id\nLEFT JOIN vehicles ON refuel_sessions.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON refuel_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  $__timeFilter(date) AND\n  locations.display_name IS NOT NULL AND\n  refuel_sessions.vehicle_vin = '$VIN'\nGROUP BY \"Operator\"\nORDER BY \"Sessions\" DESC, \"Amount\" DESC\nLIMIT 10"
    }
   ]
  }
 ]
}