# config file version
apiVersion: 1

datasources:
  - name: VWsFriend
    orgId: 1
    type: postgres
    access: proxy
    database: $DB_NAME
    user: $DB_USER
    secureJsonData:
      password: $DB_PASSWORD
    jsonData:
      sslmode: "disable"
      postgresVersion: 1200
    url: $DB_HOSTNAME:$DB_PORT
    basicAuth: false
    withCredentials: false
    isDefault: true
    editable: false
