{
 "title": "Locations",
 "tags": [
  "electric",
  "hybrid"
 ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Locations",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_location_id\",\"destination_location_id\"]) AS \"location\"\nFROM trips\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\n) AS locations\nWHERE \"location\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_locations\".city,\"destination_locations\".city]) AS \"city\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_id = start_locations.osm_id\nLEFT JOIN locations destination_locations ON trips.destination_location_id = destination_locations.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\n) AS locations\nWHERE \"city\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "States",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_locations\".state,\"destination_locations\".state]) AS \"state\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_id = start_locations.osm_id\nLEFT JOIN locations destination_locations ON trips.destination_location_id = destination_locations.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\n) AS locations\nWHERE \"state\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_locations\".country,\"destination_locations\".country]) AS \"country\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_id = start_locations.osm_id\nLEFT JOIN locations destination_locations ON trips.destination_location_id = destination_locations.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\n) AS locations\nWHERE \"country\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "Neighbourhoods",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNNEST(ARRAY[\"start_locations\".neighbourhood,\"destination_locations\".neighbourhood]) as \"Neighbourhood\",\n  COUNT(*) as \"Visits\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_id = start_locations.osm_id\nLEFT JOIN locations destination_locations ON trips.destination_location_id = destination_locations.osm_id\nWHERE\n \"start_locations\".neighbourhood IS NOT NULL AND \"destination_locations\".neighbourhood IS NOT NULL AND\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\nGROUP BY \"Neighbourhood\"\nORDER BY \"Visits\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNNEST(ARRAY[\"start_locations\".city,\"destination_locations\".city]) as \"City\",\n  COUNT(*) as \"Visits\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_id = start_locations.osm_id\nLEFT JOIN locations destination_locations ON trips.destination_location_id = destination_locations.osm_id\nWHERE\n \"start_locations\".city IS NOT NULL AND \"destination_locations\".city IS NOT NULL AND\n ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\nGROUP BY \"City\"\nORDER BY \"Visits\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "States",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNNEST(ARRAY[\"start_locations\".state,\"destination_locations\".state]) as \"State\",\n  COUNT(*) as \"Visits\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_id = start_locations.osm_id\nLEFT JOIN locations destination_locations ON trips.destination_location_id = destination_locations.osm_id\nWHERE\n \"start_locations\".state IS NOT NULL AND \"destination_locations\".state IS NOT NULL AND\n ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\nGROUP BY \"State\"\nORDER BY \"Visits\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Last visited",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  max(\"endDate\") AS \"Date\",\n  \"display_name\" AS \"Location\"\nFROM trips\nRIGHT JOIN locations ON trips.destination_location_id = locations.osm_id\nWHERE\n  $__timeFilter(\"endDate\") AND\n  trips.vehicle_vin = '$VIN'\nGROUP BY \"display_name\", \"destination_location_id\"\nORDER BY \"Date\" DESC\nLIMIT 50"
    }
   ]
  }
 ]
}