{
 "title": "Trips",
 "tags": [
  "electric",
  "hybrid"
 ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles"
   }
  ]
 },
 "panels": [
  {
   "title": "Trips",
   "type": "table",
   "gridPos": { "h": 26, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"startDate\" AS \"Start Date\",\n  start_locations.display_name AS \"Start Location\",\n  destination_location.display_name AS \"Destination Location\",\n  (\"endDate\"-\"startDate\") AS \"Duration\",\n  (\"end_mileage_km\"-\"start_mileage_km\") AS \"Length\",\n  \"end_mileage_km\" AS \"Odometer\",\n  id,\n  COALESCE((round(extract(epoch FROM \"startDate\") - 300) * 1000)::TEXT,'now-1d') AS start_date_ts,\n  COALESCE((round(extract(epoch FROM \"endDate\") + 300) * 1000)::TEXT,'now') AS end_date_ts\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  trips.vehicle_vin = '$VIN'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Longest Trips by km",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"endDate\" AS \"Date\",\n  destination_location.display_name AS \"Destination\",\n  (\"end_mileage_km\"-\"start_mileage_km\") AS \"Length\",\n  id,\n  COALESCE((round(extract(epoch FROM \"endDate\") - 10) * 1000)::TEXT,'now-1d') AS start_date_ts,\n  COALESCE((round(extract(epoch FROM \"endDate\") - 10) * 1000)::TEXT,'now') AS end_date_ts\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  (\"end_mileage_km\"-\"start_mileage_km\") IS NOT NULL AND\n  trips.vehicle_vin = '$VIN'\nORDER BY \"Length\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Longest Trips by Duration",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 17, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"endDate\" AS \"Date\",\n  destination_location.display_name AS \"Destination\",\n  (\"endDate\"-\"startDate\") AS \"Duration\",\n  id,\n  COALESCE((round(extract(epoch FROM \"endDate\") - 10) * 1000)::TEXT,'now-1d') AS start_date_ts,\n  COALESCE((round(extract(epoch FROM \"endDate\") - 10) * 1000)::TEXT,'now') AS end_date_ts\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  (\"endDate\"-\"startDate\") IS NOT NULL AND\n  trips.vehicle_vin = '$VIN'\nORDER BY \"Duration\" DESC\nLIMIT 10"
    }
   ]
  }
 ]
}