version: '3.8'
services:
  iobroker:
    image: tillsteinbach/vwsfriend-iobroker:latest
    #build: iobroker/.
    networks:
      bridge:
      backend:
        aliases:
          - iobrokerbackend
    volumes:
      - iobroker_data:/opt/iobroker
    ports:
      - 8081:8081
    environment:
      - AVAHI=false
      - HOMEKIT=false
      - INFLUXDB_ADMIN_USER=${DB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${DB_PASSWORD}
      - INFLUXDB_DB=iobroker
      - VWCONNECT_USER
      - VWCONNECT_PASSWORD
      - VWCONNECT_PIN
      - VWCONNECT_TYPE=id
      - VWCONNECT_INTERVAL
  influxdb:
    image: influxdb:1.8
    expose:
      - 8086
    networks:
      backend:
        aliases:
          - influxdbbackend
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${DB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${DB_PASSWORD}
      - INFLUXDB_DB=iobroker
    healthcheck:
      test: (wget -qO- http://localhost:8086/metrics | grep "# HELP" -q) || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:7.5.3
    ports:
      - 3001:3000
    networks:
      bridge:
      backend:
        aliases:
          - grafanabackend
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/config/grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

    environment:
      - GF_SECURITY_ADMIN_USER=${USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=natel-discrete-panel,pierosavi-imageit-panel
    healthcheck:
      test: (wget -qO- http://localhost:3000 | grep "<title>Grafana</title>" -q) || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  bridge:
  backend:

volumes:
  iobroker_data:
  influxdb_data:
  grafana_data:
