version: '3.8'
services:
  vwsfriend:
    image: tillsteinbach/vwsfriend:${VWSFRIEND_VERSION-latest}
    ports:
     - 4000:4000
    networks:
      backend:
    environment:
      - WECONNECT_USER
      - WECONNECT_PASSWORD
      - WECONNECT_INTERVAL
      - DATABASE_URL=postgresql://${DB_USER-admin}:${DB_PASSWORD-secret}@postgresdbbackend/vwsfriend
      - ADDITIONAL_PARAMETERS=--with-database --with-abrp -vv
    depends_on:
      postgresdb:
        condition: service_healthy
    healthcheck:
      test: (wget -qO- http://localhost:4000/healthcheck | grep "ok" -q) || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

  postgresdb:
    image: postgres:13
    networks:
      backend:
        aliases:
          - postgresdbbackend
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_USER=${DB_USER-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD-secret}
      - POSTGRES_DB=vwsfriend
      - TZ=UTC
      - PGTZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${DB_USER-admin} --dbname=vwsfriend"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: tillsteinbach/vwsfriend-grafana:${VWSFRIEND_GRAFANA_VERSION-latest}
    ports:
      - 3000:3000
    networks:
      bridge:
      backend:
        aliases:
          - grafanabackend
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${USERNAME-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD-secret}
      - DB_USER=${DB_USER-admin}
      - DB_PASSWORD=${DB_PASSWORD-secret}
    healthcheck:
      test: ["CMD-SHELL", "(wget -qO- http://localhost:3000/api/health | grep '\"database\": \"ok\"' -q) || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  bridge:
  backend:

volumes:
  postgresdb_data:
  grafana_data:
