version: '3.8'
services:
  vwsfriend:
    image: tillsteinbach/vwsfriend:latest
    ports:
     - 4000:4000
    networks:
      backend:
    environment:
      - WECONNECT_USER
      - WECONNECT_PASSWORD
      - WECONNECT_INTERVAL
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgresdbbackend/vwsfriend
      - ADDITIONAL_PARAMETERS=--with-database --with-abrp -vv
  postgresdb:
    image: postgres:13
    networks:
      backend:
        aliases:
          - postgresdbbackend
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=vwsfriend
      - TZ=UTC
      - PGTZ=UTC

  grafana:
    image: tillsteinbach/vwsfriend-grafana:latest
    ports:
      - 3000:3000
    networks:
      bridge:
      backend:
        aliases:
          - grafanabackend
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: (wget -qO- http://localhost:3000 | grep "<title>Grafana</title>" -q) || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  bridge:
  backend:

volumes:
  postgresdb_data:
  grafana_data:
