{
 "title": "Electric Car Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "VIN",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /^vw-connect\\.\\d+\\.[A-Z0-9]+.*/"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Projected Range",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.cruisingRangeElectric_km",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.cruisingRangeElectric_km\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "SoC" }
   ],
   "targets": [
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct",
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Projected Range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.cruisingRangeElectric_km",
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.cruisingRangeElectric_km\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Car Online State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Car is online",
     "measurement": "0_userdata.0.vw-connect.0.$VIN.online",
     "query": "SELECT last(\"value\") FROM \"0_userdata.0.vw-connect.0.$VIN.online\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Data from Car",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Letzter Abruf",
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.carCapturedTimestamp",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.carCapturedTimestamp\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quick View",
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "measurement": "vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.front",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.front\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.rear",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.rear\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "vw-connect.0.$VIN.status.climatisationSettings.targetTemperature_C",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.climatisationSettings.targetTemperature_C\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "vw-connect.0.$VIN.status.climatisationStatus.climatisationState",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.climatisationStatus.climatisationState\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.plugStatus.plugConnectionState\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.plugStatus.plugLockState\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Target Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vw-connect.0.$VIN.status.climatisationSettings.targetTemperature_C",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.climatisationSettings.targetTemperature_C\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining Climatization Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.climatisationStatus.remainingClimatisationTime_min\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch und Max Reichweite",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "lengthkm", "label": "Current Range at 100%" }
   ],
   "targets": [
    {
     "alias": "Current Range at 100%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "0_userdata.0.vw-connect.0.$VIN.currentTotalRange_km",
     "query": "SELECT mean(\"value\") FROM \"0_userdata.0.vw-connect.0.$VIN.currentTotalRange_km\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "0_userdata.0.vw-connect.0.$VIN.currentConsumption_kwhp100km",
     "query": "SELECT mean(\"value\") FROM \"0_userdata.0.vw-connect.0.$VIN.currentConsumption_kwhp100km\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Charging Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vw-connect.0.$VIN.status.climatisationStatus.remainingClimatisationTime_min",
     "query": "SELECT last(\"value\") FROM \"vw-connect.0.$VIN.status.chargingStatus.chargePower_kW\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining Charging Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vw-connect.0.$VIN.status.climatisationStatus.remainingClimatisationTime_min",
     "query": "SELECT \"value\" FROM \"vw-connect.0.$VIN.status.chargingStatus.remainingChargingTimeToComplete_min\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Efficiency" }
   ],
   "targets": [
    {
     "alias": "Efficiency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "0_userdata.0.vw-connect.0.$VIN.efficiency_pct",
     "query": "SELECT mean(\"value\") FROM \"0_userdata.0.vw-connect.0.$VIN.efficiency_pct\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "daswetter.0.NextHours.Location_1.Day_1.current.temp_value",
     "query": "SELECT mean(\"value\") FROM \"daswetter.0.NextHours.Location_1.Day_1.current.temp_value\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Charging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "kwatt", "label": "Charge Power" }
   ],
   "targets": [
    {
     "alias": "Charge Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct",
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.chargingStatus.chargePower_kW\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Charge Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.cruisingRangeElectric_km",
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.chargingStatus.chargeRate_kmph\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Online State",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 32 },
   "targets": [
    {
     "alias": "Car state",
     "measurement": "0_userdata.0.vw-connect.0.$VIN.online",
     "query": "SELECT \"value\" FROM \"0_userdata.0.vw-connect.0.$VIN.online\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Climatization",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 36 },
   "targets": [
    {
     "alias": "Climatization",
     "measurement": "vw-connect.0.$VIN.status.climatisationStatus.climatisationState",
     "query": "SELECT \"value\" FROM \"vw-connect.0.$VIN.status.climatisationStatus.climatisationState\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Front Window Heating",
     "measurement": "vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.front",
     "query": "SELECT \"value\" FROM \"vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.front\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Rear Window Heating",
     "measurement": "vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.rear",
     "query": "SELECT \"value\" FROM \"vw-connect.0.$VIN.status.windowHeatingStatus.windowHeatingStatus.rear\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Charging State",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 44 },
   "targets": [
    {
     "alias": "Charging State",
     "measurement": "vw-connect.0.$VIN.status.chargingStatus.chargingState",
     "query": "SELECT \"value\" FROM \"vw-connect.0.$VIN.status.chargingStatus.chargingState\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}