"""add settings

Revision ID: 06a5ec0a1af0
Revises: 90636c798967
Create Date: 2021-09-08 08:38:26.189013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a5ec0a1af0'
down_revision = '90636c798967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_of_length', sa.Enum('KM', 'MI', name='unitoflength'), nullable=True),
    sa.Column('unit_of_temperature', sa.Enum('C', 'F', name='unitoftemperature'), nullable=True),
    sa.Column('grafana_url', sa.String(), nullable=True),
    sa.Column('vwsfriend_url', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
