{
 "title": "Aggregated Trip Details",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"nickname\" || ' (' || \"model\" || ' - ' || \"carType\" || ')' FROM vehicles LEFT JOIN vehicle_settings ON vehicles.VIN = vehicle_settings.vehicle_vin WHERE vehicle_settings.hide IS NOT True ORDER BY vehicle_settings.sorting_order ASC"
   },
   {
    "name": "car_timezone",
    "label": "The Cars timezone",
    "query": "SELECT COALESCE(timezone, 'UTC') FROM vehicle_settings WHERE vehicle_vin='$VIN'"
   },
   {
    "name": "start_location",
    "label": "Start",
    "query": "SELECT\n   \"start_location_id\" || ':' || COALESCE(start_locations.\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', start_locations.name, start_locations.amenity), nullif(CONCAT_WS(' ', start_locations.road, start_locations.house_number), '')), start_locations.neighbourhood, start_locations.city, start_locations.postcode, start_locations.country)) AS \"Start Location\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nWHERE \"start_location_id\" IS NOT NULL\nORDER BY COALESCE(start_locations.\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', start_locations.name, start_locations.amenity), nullif(CONCAT_WS(' ', start_locations.road, start_locations.house_number), '')), start_locations.neighbourhood, start_locations.city, start_locations.postcode, start_locations.country))"
   },
   {
    "name": "vwsfriend_url",
    "query": "SELECT vwsfriend_url FROM settings LIMIT 1"
   },
   {
    "name": "destination_location",
    "label": "Destination",
    "query": "SELECT\n   \"destination_location_id\" || ':' || COALESCE(destination_locations.\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', destination_locations.name, destination_locations.amenity), nullif(CONCAT_WS(' ', destination_locations.road, destination_locations.house_number), '')), destination_locations.neighbourhood, destination_locations.city, destination_locations.postcode, destination_locations.country)) AS \"Destination Location\"\nFROM trips\nLEFT JOIN locations destination_locations ON trips.\"destination_location_id\" = destination_locations.osm_id\nWHERE \"destination_location_id\" IS NOT NULL\nORDER BY COALESCE(destination_locations.\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', destination_locations.name, destination_locations.amenity), nullif(CONCAT_WS(' ', destination_locations.road, destination_locations.house_number), '')), destination_locations.neighbourhood, destination_locations.city, destination_locations.postcode, destination_locations.country))"
   }
  ]
 },
 "panels": [
  {
   "title": "Trip",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${start_location:singlequote} = 'none' OR ${destination_location:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No start or destination location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  latitude,\n  longitude\nFROM locations\nWHERE\n  osm_id = $start_location\nUNION\nSELECT\n  latitude,\n  longitude\nFROM locations\nWHERE\n  osm_id = $destination_location"
    },
    {
     "rawSql": "SELECT\n  latitude,\n  longitude,\n  COALESCE(\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', name, amenity), nullif(CONCAT_WS(' ', road, house_number), '')), neighbourhood, city, postcode, country)) AS \"Location\"\nFROM locations\nWHERE\n  osm_id = $start_location"
    },
    {
     "rawSql": "SELECT\n  latitude,\n  longitude,\n  COALESCE(\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', name, amenity), nullif(CONCAT_WS(' ', road, house_number), '')), neighbourhood, city, postcode, country)) AS \"Location\"\nFROM locations\nWHERE\n  osm_id = $destination_location"
    }
   ]
  },
  {
   "title": "Details",
   "type": "stat",
   "description": "Details of the trips. On some cars not all data is provided and thus sections may remain empty.",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "CREATE extension IF NOT EXISTS cube;\nCREATE extension IF NOT EXISTS earthdistance;\n\nDO $$ \nBEGIN\nIF ${start_location:singlequote} = 'none' OR ${destination_location:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No start or destination location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  COUNT(*) AS \"Number of trips\",\n  MAX(\"Distance\") AS \"Distance\",\n  MIN(\"Length\") AS \"Minimum length\",\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY \"Length\") AS \"Median length\",\n  MAX(\"Length\") AS \"Maximum length\",\n  SUM(\"Length\") AS \"Total length\",\n  MIN(\"Duration\") AS \"Minimum duration\",\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY \"Duration\") AS \"Median duration\",\n  stddev_samp(\"Duration\") AS \"Std. dev. duration\",\n  MAX(\"Duration\") AS \"Maximum duration\",\n  SUM(\"Duration\") AS \"Total duration\"\nFROM\n(SELECT\n  id AS \"id\",\n  EXTRACT(EPOCH FROM(\"endDate\"-\"startDate\")) AS \"Duration\",\n  (point(start_locations.longitude, start_locations.latitude)<@>point(destination_location.longitude, destination_location.latitude)) * 1.609344 AS \"Distance\",\n  \"end_mileage_km\"-\"start_mileage_km\" AS \"Length\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  start_location_id = $start_location AND\n  destination_location_id = $destination_location AND\n  vehicle_vin = '$VIN') AS tripdata"
    }
   ]
  },
  {
   "title": "Duration distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${start_location:singlequote} = 'none' OR ${destination_location:singlequote} = 'none'THEN\n  RAISE EXCEPTION 'No start or destination location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  EXTRACT(EPOCH FROM(\"endDate\"-\"startDate\")) AS \"Duration\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nLEFT JOIN trip_tag ON trips.id = trip_tag.trips_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  start_location_id = $start_location AND\n  destination_location_id = $destination_location AND\n  vehicle_vin = '$VIN'\nGROUP BY 1\nORDER BY 1 DESC\n"
    }
   ]
  },
  {
   "title": "Trips on this route",
   "type": "table",
   "description": "List of all trips between start and destination recorded. Not all attributes can be filled automatically. If you want to make additions or changes use the ⚙ button at the end of each row.",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${start_location:singlequote} = 'none' OR ${destination_location:singlequote} = 'none'THEN\n  RAISE EXCEPTION 'No start or destination location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  \"startDate\" AS \"Start Date\",\n  EXTRACT('epoch' FROM(\"endDate\"-\"startDate\")) AS \"Duration\",\n  (\"end_mileage_km\"-\"start_mileage_km\") AS \"Length\",\n  \"end_mileage_km\" AS \"Odometer\",\n  '⚙' AS \"Edit\",\n  id,\n  COALESCE((round(extract(epoch FROM \"startDate\") - 300) * 1000)::TEXT,'now-1d') AS start_date_ts,\n  COALESCE((round(extract(epoch FROM \"endDate\") + 300) * 1000)::TEXT,'now') AS end_date_ts\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nLEFT JOIN trip_tag ON trips.id = trip_tag.trips_id\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  start_location_id = $start_location AND\n  destination_location_id = $destination_location AND\n  vehicle_vin = '$VIN'\nGROUP BY 1,2,3,4,5,6,7,8\nORDER BY 1 DESC\n"
    }
   ]
  },
  {
   "title": "Hourly distribution in timezone $car_timezone",
   "type": "natel-plotly-panel",
   "description": "Distribution of the trip occurrences over the day.\nFor meaningful values wait until a significant number of trips were recorded. Change timezone in vehicle settings.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${start_location:singlequote} = 'none' OR ${destination_location:singlequote} = 'none'THEN\n  RAISE EXCEPTION 'No start or destination location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  EXTRACT(HOUR FROM ((\"startDate\" AT TIME ZONE 'UTC') AT TIME ZONE COALESCE(vehicle_settings.timezone, 'UTC')))\n  + (ROUND((EXTRACT(MINUTE FROM \"startDate\")/30)::numeric)/2) AS \"Hour\",\n (SUM(EXTRACT(EPOCH FROM(\"endDate\"-\"startDate\"))) / CAST( SUM(SUM(EXTRACT(EPOCH FROM(\"endDate\"-\"startDate\")))) over () as FLOAT) * 100) AS \"Number\",\n ROUND((SUM(EXTRACT(EPOCH FROM(\"endDate\"-\"startDate\"))) / CAST( SUM(SUM(EXTRACT(EPOCH FROM(\"endDate\"-\"startDate\")))) over () as FLOAT) * 100))::TEXT || '% of total time on this route' AS \"Text\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nLEFT JOIN trip_tag ON trips.id = trip_tag.trips_id\nLEFT JOIN vehicle_settings ON trips.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  start_location_id = $start_location AND\n  destination_location_id = $destination_location AND\n  trips.vehicle_vin = '$VIN'\nGROUP BY \"Hour\"\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Duration by time in timezone $car_timezone",
   "type": "natel-plotly-panel",
   "description": "Duration of the trip occurrences over the day.\nFor meaningful values wait until a significant number of trips were recorded. Change timezone in vehicle settings.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${start_location:singlequote} = 'none' OR ${destination_location:singlequote} = 'none'THEN\n  RAISE EXCEPTION 'No start or destination location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT * FROM (\nSELECT\n  EXTRACT(HOUR FROM ((\"startDate\" AT TIME ZONE 'UTC') AT TIME ZONE COALESCE(vehicle_settings.timezone, 'UTC')))\n  + (ROUND(EXTRACT(MINUTE FROM \"startDate\" AT TIME ZONE 'UTC')/10)/6) AS \"Hour\",\n  MIN(extract('epoch' from \"endDate\"-\"startDate\"))/60 AS \"Minimum\",\n  MAX(extract('epoch' from \"endDate\"-\"startDate\"))/60 AS \"Maximum\",\n  AVG(extract('epoch' from \"endDate\"-\"startDate\"))/60 AS \"Average\",\n  COUNT(*) AS \"Samples\",\n  'Based on ' || COUNT(*) || ' samples' AS \"Max. Text\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.\"start_location_id\" = start_locations.osm_id\nLEFT JOIN locations destination_location ON trips.\"destination_location_id\" = destination_location.osm_id\nLEFT JOIN trip_tag ON trips.id = trip_tag.trips_id\nLEFT JOIN vehicle_settings ON trips.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  ($__timeFilter(\"startDate\") OR $__timeFilter(\"endDate\")) AND\n  start_location_id = $start_location AND\n  destination_location_id = $destination_location AND\n  trips.vehicle_vin = '$VIN'\nGROUP BY \"Hour\"\nORDER BY 1) AS result\nWHERE\n  \"Samples\" > 1\n"
    }
   ]
  },
  {
   "title": "Start Location",
   "type": "stat",
   "description": "Start of the trip. If no data is shown your car does not provide location information.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "\nDO $$ \nBEGIN\nIF ${start_location:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No start location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  name AS \"Name\",\n  amenity AS \"Amenity\",\n  (road || COALESCE(' '||house_number, '')) AS \"Street\",\n  neighbourhood AS \"Neighbourhood\",\n  postcode AS \"Postcode\",\n  city AS \"City\",\n  state AS \"State\",\n  country AS \"Country\"\nFROM locations\nWHERE\n  osm_id = $start_location"
    }
   ]
  },
  {
   "title": "Destination Location",
   "type": "stat",
   "description": "End of the trip. If no data is shown your car does not provide location information.",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "\nDO $$ \nBEGIN\nIF ${destination_location:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No destination location was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  name AS \"Name\",\n  amenity AS \"Amenity\",\n  (road || COALESCE(' '||house_number, '')) AS \"Street\",\n  neighbourhood AS \"Neighbourhood\",\n  postcode AS \"Postcode\",\n  city AS \"City\",\n  state AS \"State\",\n  country AS \"Country\"\nFROM locations\nWHERE\n  osm_id = $destination_location"
    }
   ]
  }
 ]
}