{
 "title": "Charge Session",
 "tags": [
  "electric",
  "hybrid"
 ],
 "templating": {
  "list": [
   { "name": "id" },
   { "name": "VIN" }
  ]
 },
 "panels": [
  {
   "title": "Battery Level",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "SoC" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"cruisingRangeElectric_km\" AS \"Electric Range\"\nFROM battery\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1  "
    },
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"currentSOC_pct\" AS \"Battery SoC\"\nFROM battery\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Times",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  connected AS \"Connected\",\n  locked AS \"Locked\",\n  started AS \"Started\",\n  ended AS \"Ended\",\n  unlocked AS \"Unlocked\",\n  disconnected AS \"Disconnected\"\nFROM charging_sessions\nWHERE\n  id = $id"
    }
   ]
  },
  {
   "title": "Charging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kwatt", "label": "Charge Power" }
   ],
   "targets": [
    {
     "alias": "Charge Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct",
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.chargingStatus.chargePower_kW\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"chargePower_kW\" AS \"Charge Power\"\nFROM charges\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1  "
    },
    {
     "alias": "Charge Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vw-connect.0.$VIN.status.batteryStatus.cruisingRangeElectric_km",
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.chargingStatus.chargeRate_kmph\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"chargeRate_kmph\" AS \"Charge Rate\"\nFROM charges\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1  "
    }
   ]
  },
  {
   "title": "Details",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"maxChargeCurrentACSetting\" AS \"Maximum AC Power Setting\",\n  \"targetSOCSetting_pct\" AS \"Target SoC Setting\",\n  \"maximumChargePower_kW\" AS \"Maximum Charge Power\",\n  \"acdc\" AS \"AC/DC\",\n  \"startSOC_pct\" AS \"% Start\",\n  \"endSOC_pct\" AS \"% End\",\n  (\"endSOC_pct\" - \"startSOC_pct\") * (\n    CASE WHEN vehicles.\"carType\" = 'ELECTRIC' THEN vehicle_settings.\"primary_capacity\"::NUMERIC\n         ELSE vehicle_settings.\"secondary_capacity\"::NUMERIC\n    END\n    / 100::NUMERIC) AS \"Amount\",\n  \"mileage_km\" AS \"Odometer\"\nFROM charging_sessions\nLEFT JOIN vehicles ON charging_sessions.vehicle_vin = vehicles.vin\nLEFT JOIN vehicle_settings ON charging_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nWHERE\n  id = $id"
    }
   ]
  },
  {
   "title": "Charger",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  chargers.name AS \"Name\",\n  chargers.address AS \"Address\",\n  chargers.max_power AS \"Max Power\",\n  chargers.num_spots AS \"Spots\",\n  operators.name AS \"Operator\"\nFROM charging_sessions\nLEFT JOIN chargers ON charger_id = chargers.id\nLEFT JOIN operators ON operator_id = operators.id\nWHERE\n  charging_sessions.id = $id"
    }
   ]
  },
  {
   "title": "Charging Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(connected),\n  unnest(ARRAY[position_latitude, chargers.latitude]) AS latitude\nFROM charging_sessions\nLEFT JOIN chargers ON charging_sessions.charger_id = chargers.id\nWHERE\n  charging_sessions.id = $id"
    },
    {
     "rawSql": "SELECT\n  $__time(connected),\n  unnest(ARRAY[position_longitude, chargers.longitude]) AS longitude\nFROM charging_sessions\nLEFT JOIN chargers ON charging_sessions.charger_id = chargers.id\nWHERE\n  charging_sessions.id = $id"
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  locations.name AS \"Name\",\n  locations.amenity AS \"Amenity\",\n  (locations.road || COALESCE(' '||locations.house_number, '')) AS \"Street\",\n  locations.neighbourhood AS \"Neighbourhood\",\n  locations.postcode AS \"Postcode\",\n  locations.city AS \"City\",\n  locations.state AS \"State\",\n  locations.country AS \"Country\"\nFROM charging_sessions\nLEFT JOIN locations on charging_sessions.location_id = locations.osm_id\nWHERE\n  id = $id"
    }
   ]
  }
 ]
}