{
 "title": "Refuel Session",
 "tags": [ "internal" ],
 "templating": {
  "list": [
   { "name": "id", "query": "none" },
   { "name": "VIN", "query": "none" },
   {
    "name": "vwsfriend_url",
    "query": "SELECT vwsfriend_url FROM settings LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Gas Station Location",
   "type": "panodata-map-panel",
   "description": "Location of the car when refueling (green) and the detected gas station (red). If no location is shown you can add the location data using the edit button.",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Refueling dashboard';\nEND IF;\nEND $$;\n(SELECT\n  position_latitude AS latitude,\n  position_longitude AS longitude,\n  \"realRefueled_l\" AS metric,\n  'Car Position' AS label\nFROM refuel_sessions\nLEFT JOIN locations ON refuel_sessions.location_id = locations.osm_id\nWHERE\n  refuel_sessions.id = $id)\nUNION\n(SELECT\n  latitude AS latitude,\n  longitude AS longitude,\n  \"realRefueled_l\" AS metric,\n  display_name AS label\nFROM refuel_sessions\nLEFT JOIN locations ON refuel_sessions.location_id = locations.osm_id\nWHERE\n  refuel_sessions.id = $id)"
    }
   ]
  },
  {
   "title": "Times",
   "type": "stat",
   "description": "Time of the refueling session.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Refueling dashboard';\nEND IF;\nEND $$;\nSELECT\n  date AS \"Date\"\nFROM refuel_sessions\nWHERE\n  id = $id"
    }
   ]
  },
  {
   "title": "Details",
   "type": "stat",
   "description": "Details of the refueling session. The amount is estimated based on the fill level before and after refueling. If you want to work with the real amount and cost in the statistics you can add this data using the edit button.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Refueling dashboard';\nEND IF;\nEND $$;\nSELECT\n  \"startSOC_pct\" AS \"% Start\",\n  \"endSOC_pct\" AS \"% End\",\n   (\"endSOC_pct\" - \"startSOC_pct\") * (vehicle_settings.\"primary_capacity\"::NUMERIC / 100::NUMERIC) AS \"Amount (estimated)\",\n  \"realRefueled_l\" AS \"Amount (real)\",\n  \"realCost_ct\"::NUMERIC/100::NUMERIC AS \"Cost (real)\",\n  \"mileage_km\" AS \"Odometer\",\n  string_agg(refuel_tag.tag_name, ', ') AS \"Tags\"\nFROM refuel_sessions\nLEFT JOIN vehicle_settings ON refuel_sessions.vehicle_vin = vehicle_settings.vehicle_vin\nLEFT JOIN refuel_tag on refuel_sessions.id = refuel_tag.refuel_sessions_id\nWHERE\n  id = $id\nGROUP BY \"startSOC_pct\", \"endSOC_pct\", vehicle_settings.\"primary_capacity\", \"realRefueled_l\", \"realCost_ct\", \"mileage_km\""
    }
   ]
  },
  {
   "title": "Station Location",
   "type": "stat",
   "description": "Location of the refueling. If no location is provided your car probably does not provide a location. You can set it manually by changing the session with the edit button.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Refueling dashboard';\nEND IF;\nEND $$;\nSELECT\n  locations.name,\n  locations.amenity,\n  locations.road,\n  locations.house_number,\n  locations.neighbourhood,\n  locations.postcode,\n  locations.city,\n  locations.state,\n  locations.country\nFROM refuel_sessions\nLEFT JOIN locations on refuel_sessions.location_id = locations.osm_id\nWHERE\n  id = $id"
    }
   ]
  }
 ]
}