{
 "title": "Server Statistics",
 "tags": [ "internal" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total HTTP errors",
   "type": "stat",
   "description": "Total number of HTTP errors during the selected time.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM weconnect_errors\nWHERE\n  $__timeFilter(\"datetime\") AND\n  \"errortype\" = 'HTTP'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Server Response Time",
   "type": "timeseries",
   "description": "Response time of the server when fetching data",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"datetime\", $__interval),\n  MIN(\"min\") AS \"minimum\",\n  AVG(\"avg\") AS \"average\",\n  MAX(\"max\") AS \"maximum\",\n  AVG(\"total\") AS \"total\"\nFROM weconnect_responsetime\nWHERE\n  $__timeFilter(\"datetime\")\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Number of errors over time.",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"datetime\", $__interval, 0),\n  COUNT(*) AS \"HTTP Error\"\nFROM weconnect_errors\nWHERE\n  $__timeFilter(\"datetime\") AND\n  \"errortype\" = 'HTTP'\nGROUP BY time\nORDER BY time"
    }
   ]
  }
 ]
}