{
 "title": "Trip Details",
 "tags": [ "internal" ],
 "templating": {
  "list": [
   { "name": "id" },
   { "name": "VIN" },
   {
    "name": "vwsfriend_url",
    "query": "SELECT vwsfriend_url FROM settings LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"cruisingRangeElectric_km\" AS \"Electric Range\"\nFROM battery\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1  "
    },
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "rawSql": "SELECT\n  \"carCapturedTimestamp\" AS \"time\",\n  \"currentSOC_pct\" AS \"Battery SoC\"\nFROM battery\nWHERE\n  $__timeFilter(\"carCapturedTimestamp\") AND\n  vehicle_vin = '$VIN'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Details",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "CREATE extension IF NOT EXISTS cube;\nCREATE extension IF NOT EXISTS earthdistance;\n\nSELECT\n  \"startDate\" AS \"Start Date\",\n  \"endDate\" AS \"End Date\",\n  (\"endDate\"-\"startDate\") AS \"Duration\",\n  (point(start_position_longitude, start_position_latitude)<@>point(destination_position_longitude, destination_position_latitude)) * 1.609344 as \"Distance\",\n  (\"end_mileage_km\"-\"start_mileage_km\") AS \"Length\",\n  \"end_mileage_km\" AS \"Odometer\"\nFROM trips\nWHERE\n  id = $id"
    }
   ]
  },
  {
   "title": "Trip",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"startDate\"),\n  trips.start_position_latitude AS latitude\nFROM trips\nWHERE\n  trips.id = $id\nUNION\nSELECT\n  $__time(\"endDate\"),\n  trips.destination_position_latitude AS latitude\nFROM trips\nWHERE\n  trips.id = $id"
    },
    {
     "rawSql": "SELECT\n  $__time(\"startDate\"),\n  trips.start_position_longitude AS longitude \nFROM trips\nWHERE\n  trips.id = $id\nUNION\nSELECT\n  $__time(\"endDate\"),\n  trips.destination_position_longitude AS longitude \nFROM trips\nWHERE\n  trips.id = $id"
    }
   ]
  },
  {
   "title": "Start Location",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  locations.name AS \"Name\",\n  locations.amenity AS \"Amenity\",\n  (locations.road || COALESCE(' '||locations.house_number, '')) AS \"Street\",\n  locations.neighbourhood AS \"Neighbourhood\",\n  locations.postcode AS \"Postcode\",\n  locations.city AS \"City\",\n  locations.state AS \"State\",\n  locations.country AS \"Country\"\nFROM trips\nLEFT JOIN locations on trips.start_location_id = locations.osm_id\nWHERE\n  id = $id"
    }
   ]
  },
  {
   "title": "Destination Location",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  locations.name AS \"Name\",\n  locations.amenity AS \"Amenity\",\n  (locations.road || COALESCE(' '||locations.house_number, '')) AS \"Street\",\n  locations.neighbourhood AS \"Neighbourhood\",\n  locations.postcode AS \"Postcode\",\n  locations.city AS \"City\",\n  locations.state AS \"State\",\n  locations.country AS \"Country\"\nFROM trips\nLEFT JOIN locations on trips.destination_location_id = locations.osm_id\nWHERE\n  id = $id"
    }
   ]
  }
 ]
}