name: Docker-Compose CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/compose.yml'
      - 'docker-compose*.yml'
      - '.env'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose-file: [docker-compose.yml, docker-compose-homekit-host.yml, docker-compose-homekit-macvlan.yml]
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f ${{ matrix.compose-file }} --env-file .env up -d
    - name: Container Status
      run: docker ps -a
    - name: Check running containers
      run: |
        docker ps -a | grep -q 'Up.*\(health:\sstarting\).*vwsfriend_vwsfriend_1'
        docker ps -a | grep -q 'Up.*\(health:\sstarting\).*vwsfriend_grafana_1'
        docker ps -a | grep -q 'Up.*\(health:\sstarting\).*vwsfriend_postgresdb_1'
      
      shell: bash
    - name: Let containers run for 60s
      uses: juliangruber/sleep-action@v1
      with:
        time: 60s
    - name: Check logs for vwsfriend
      run: docker logs vwsfriend_vwsfriend_1
    - name: Check logs for postgresdb
      run: docker logs vwsfriend_postgresdb_1
    - name: Check logs for grafana
      run: docker logs vwsfriend_grafana_1
    - name: Container Status
      run: docker ps -a
    - name: Check running containers again
      run: |
        docker ps -a | grep -q 'Up.*\(healthy\).*vwsfriend_grafana_1'
        docker ps -a | grep -q 'Up.*\(healthy\).*vwsfriend_postgresdb_1'
