name: Docker-Compose CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - docker-compose*.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose --env-file .env up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs for iobroker
      run: docker logs vwsfriend_iobroker_1
    - name: Check logs for influxdb
      run: docker logs vwsfriend_influxdb_1
    - name: Check logs for grafana
      run: docker logs vwsfriend_grafana_1
