name: Docker-Compose CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/compose.yml'
      - 'docker-compose*.yml'

jobs:
  build:
    strategy:
      matrix:
        compose-file: [docker-compose.yml, docker-compose-homekit-host.yml, docker-compose-homekit-macvlan.yml]
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f ${{ matrix.compose-file }} --env-file .env up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs for iobroker
      run: docker logs vwsfriend_vwsfriend_1
    - name: Check logs for influxdb
      run: docker logs vwsfriend_postgresdb_1
    - name: Check logs for grafana
      run: docker logs vwsfriend_grafana_1
