name: Update Docker Hub Description for Grafana
on:
  push:
    branches:
      - main
    paths:
      - grafana/README.md
      - .github/workflows/grafana-dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3.4.1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: tillsteinbach/vwsfriend-grafana
        short-description: "Grafana provisioned for VWsFriend Software. See: https://github.com/tillsteinbach/VWsFriend/"
        readme-filepath: ./grafana/README.md
