name: Update Docker Hub Description for VWsFriend
on:
  push:
    branches:
      - main
    paths:
      - vwsfriend/README.md
      - .github/workflows/grafana-vwsfriend-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3.4.2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: tillsteinbach/vwsfriend
        short-description: "VWsFriend Software. See: https://github.com/tillsteinbach/VWsFriend/"
        readme-filepath: ./README.md
