name: Update Docker Hub Description for ioBroker
on:
  push:
    branches:
      - master
    paths:
      - iobroker/README.md
      - .github/workflows/iobroker-dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: tillsteinbach/vwsfriend-iobroker
        short-description: "ioBroker provisioned for VWsFriend Software. See: https://github.com/tillsteinbach/VWsFriend/"
        readme-filepath: ./iobroker/README.md
